// What the shop owner can edit, and how each field is shown in the admin panel.
// Each section is saved as one document in Supabase `site_content` under its `key`.
import { PRODUCTS, CATEGORIES, SETS, STORY, PALETTES } from '../data/products.js';
import { SITE, PAYMENTS, TRUST, LOOKBOOK, SERVICES, FILMS } from '../data/site.js';
import { WRITTEN_REVIEWS } from '../data/reviews.js';
import { ANNOUNCEMENT } from '../data/announcement.js';
import { HOMEPAGE, HOMEPAGE_SECTIONS, SOCIALS, PLATFORMS, STORES, VIDEOS, SEO } from '../data/homepage.js';
import { MODELS, customKind } from '../data/shapes.js';

const clone = (v) => JSON.parse(JSON.stringify(v));

export const SHAPES = [
  ['none', 'None: show only the photos and films'],
  ['gachKouto', 'Tall tiered box (gach kouto)'],
  ['sindoorKouto', 'Small round box (sindoor kouto)'],
  ['kunke', 'Small pot (kunke)'],
  ['darpan', 'Hand mirror (darpan)'],
  ['piri', 'Low wooden seat (piri)'],
  ['paanPata', 'Pair of betel leaves'],
  ['mukut', 'Bride\'s crown (mukut)'],
  ['topor', 'Groom\'s crown (topor)'],
  ['thalaSet', 'Plate and bowl set (thala)'],
  ['punjabi', 'Kurta / punjabi'],
  ['archPanel', 'Arched painted panel'],
  ['backdrop', 'Stage backdrop'],
  ['flowerDala', 'Engagement platter (round tray with a rose hoop)'],
  ['kulo', 'Khoi daan kulo (arched velvet panel in a cane frame)'],
];

const palettes = () => Object.entries(PALETTES).map(([id, p]) => [id, p.label]);
const films = () => Object.entries(FILMS).map(([id, f]) => [id, f.title]);
// Options that depend on other sections are read live from the admin's working copy.
const productOptions = (ctx) => (ctx.data.products || []).map((p) => [p.id, p.en || p.id]);
// The 3D shape list: None, the built-in shapes, then the shop's uploaded models (from "3D models").
const shapeOptions = (ctx) => [
  ...SHAPES,
  ...(ctx?.data?.models?.custom || []).filter((m) => m.id && m.file).map((m) => [customKind(m.id), `${m.name || m.id} (your upload)`]),
];
const categoryOptions = (ctx) => (ctx.data.categories || []).map((c) => [c.id, c.label || c.id]);

const mediaFields = [
  { key: 'type', label: 'Kind', type: 'select', options: [['photo', 'Photo'], ['reel', 'Film (from the shop\'s film library)']], default: 'photo' },
  { key: 'id', label: 'Photo or film', type: 'media', required: true },
  { key: 'title', label: 'Caption (optional)', type: 'text' },
];

export const SECTIONS = [
  {
    // Shown on its own screen (admin/modelsView.js), not the usual form.
    key: 'models',
    title: '3D models',
    icon: '🧊',
    kind: 'object',
    intro: 'Every 3D model on the website, which products use it, and your own uploaded models.',
    defaults: () => clone(MODELS),
    fields: [
      { key: 'off', label: 'Built-in shapes switched off', type: 'multi', options: () => SHAPES.filter(([k]) => k !== 'none') },
      { key: 'custom', label: 'Your uploaded models', type: 'list', of: [
        { key: 'id', label: 'Code', type: 'slug', required: true },
        { key: 'name', label: 'Name', type: 'text', required: true },
        { key: 'file', label: 'File', type: 'text', required: true },
        { key: 'hidden', label: 'Switched off', type: 'bool' },
      ] },
    ],
  },
  {
    key: 'products',
    title: 'Products',
    icon: '🏺',
    kind: 'list',
    intro: 'Everything in the collection. Hidden products stay saved but do not appear on the site.',
    itemTitle: (p) => p.en || 'New product',
    thumb: (p) => (p.media || []).find((m) => m && m.id && m.type !== 'reel')?.id,
    itemSub: (p) => `${p.bn || ''}${p.priceFrom ? ` · from ₹${p.priceFrom}` : ''}${p.hidden ? ' · hidden' : ''}`,
    defaults: () => clone(PRODUCTS),
    blank: () => ({
      id: '', en: '', bn: '', category: 'ritual', line: '', story: '', priceFrom: 0,
      styles: ['sindoor'], combos: [{ id: 'single', label: 'Single piece', add: 0 }],
      // New products start with photos and films only; a 3D model is optional.
      customizable: true, leadDays: 7, model: { kind: 'none' }, media: [],
    }),
    normalize: (p) => ({ ...p, model: p.model?.image ? p.model : { kind: p.model?.kind || 'none' } }),
    fields: [
      { key: 'en', label: 'Name (English)', type: 'text', required: true },
      { key: 'bn', label: 'Name (Bengali)', type: 'text', lang: 'bn' },
      { advanced: true, key: 'id', label: 'Web address name', type: 'slug', from: 'en', required: true, help: 'Used in the page link, e.g. /p/gach-kouto/. Lowercase letters, numbers and dashes. Avoid changing it once shared.' },
      { key: 'category', label: 'Category', type: 'select', options: categoryOptions, required: true },
      { key: 'priceFrom', label: 'Price from (₹)', type: 'number', min: 0, required: true },
      { key: 'line', label: 'One-line summary', type: 'text', help: 'Shown under the name in the collection.' },
      { key: 'story', label: 'Full description', type: 'textarea' },
      { key: 'media', label: 'Photos and films', type: 'list', of: mediaFields, itemTitle: (m) => m.title || m.id || 'New photo', help: 'The first photo is the one shown in the collection grid.' },
      { key: 'model.kind', label: '3D model (optional)', type: 'select', options: shapeOptions, required: true, noStar: true, default: 'none', help: 'Leave as “None” to show only your photos and films. To let customers turn the piece around in 3D, pick the closest shape, or one of your own models from “3D models” in the menu.' },
      { key: 'styles', label: 'Colourways offered', type: 'multi', options: palettes, required: true, help: 'The first one is shown by default.' },
      { key: 'combos', label: 'Options and add-ons', type: 'list', of: [
        { key: 'label', label: 'Option name', type: 'text', required: true },
        { key: 'add', label: 'Extra price (₹)', type: 'number', min: 0 },
        { advanced: true, key: 'id', label: 'Option code', type: 'slug', from: 'label' },
      ], itemTitle: (c) => `${c.label || 'New option'}${c.add ? ` (+₹${c.add})` : ''}` },
      { key: 'leadDays', label: 'Days to make', type: 'number', min: 0 },
      { key: 'customizable', label: 'Can be personalised (names, portraits, colours)', type: 'bool' },
      { advanced: true, key: 'customHelp', label: 'Personalisation hint for customers', type: 'text' },
      { advanced: true, key: 'model.image', label: 'Painting on the panel (arched panel shape only)', type: 'media', photoOnly: true },
      { key: 'hidden', label: 'Hide from the site', type: 'bool' },
    ],
  },
  {
    key: 'categories',
    title: 'Categories',
    icon: '🗂️',
    kind: 'list',
    intro: 'The groups the collection is organised into. Their order here is the order on the site.',
    itemTitle: (c) => c.label || 'New category',
    itemSub: (c) => c.bn || '',
    defaults: () => clone(CATEGORIES.filter((c) => c.id !== 'all')),
    blank: () => ({ id: '', label: '', bn: '', line: '' }),
    fields: [
      { key: 'label', label: 'Name (English)', type: 'text', required: true },
      { key: 'bn', label: 'Name (Bengali)', type: 'text', lang: 'bn' },
      { advanced: true, key: 'id', label: 'Category code', type: 'slug', from: 'label', required: true, help: 'Products point at this code. Avoid changing it.' },
      { key: 'line', label: 'Short description', type: 'text' },
    ],
  },
  {
    key: 'sets',
    title: 'Bridal sets',
    icon: '🎁',
    kind: 'list',
    intro: 'Bundles of products sold together at one price.',
    itemTitle: (s) => s.en || 'New set',
    itemSub: (s) => `${(s.items || []).length} pieces${s.price ? ` · ₹${s.price}` : ''}${s.hidden ? ' · hidden' : ''}`,
    defaults: () => clone(SETS),
    blank: () => ({ id: '', en: '', bn: '', line: '', items: [], price: 0 }),
    fields: [
      { key: 'en', label: 'Name (English)', type: 'text', required: true },
      { key: 'bn', label: 'Name (Bengali)', type: 'text', lang: 'bn' },
      { advanced: true, key: 'id', label: 'Set code', type: 'slug', from: 'en', prefix: 'set-', required: true },
      { key: 'price', label: 'Set price (₹)', type: 'number', min: 0, required: true },
      { key: 'line', label: 'One-line summary', type: 'text' },
      { key: 'items', label: 'Products in this set', type: 'multi', options: productOptions, required: true },
      { key: 'hidden', label: 'Hide from the site', type: 'bool' },
    ],
  },
  {
    key: 'reviews',
    title: 'Customer reviews',
    icon: '⭐',
    kind: 'list',
    intro: 'Add only real reviews customers sent you, shown with their permission. Reviews sent from the website arrive by WhatsApp or email; copy the ones you approve here.',
    itemTitle: (r) => r.title || r.name || 'New review',
    itemSub: (r) => `${'★'.repeat(Number(r.rating) || 0)} ${r.name || ''}${r.hidden ? ' · hidden' : ''}`,
    defaults: () => clone(WRITTEN_REVIEWS),
    blank: () => ({ product: '', name: '', place: '', date: new Date().toISOString().slice(0, 10), rating: 5, title: '', text: '', style: '', verified: true }),
    newFirst: true,
    fields: [
      { key: 'product', label: 'Product', type: 'select', options: productOptions, required: true },
      { key: 'name', label: 'Customer name (as they agreed to be shown)', type: 'text', required: true },
      { key: 'place', label: 'Town (optional)', type: 'text' },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'rating', label: 'Stars', type: 'select', options: [[5, '★★★★★ 5'], [4, '★★★★ 4'], [3, '★★★ 3'], [2, '★★ 2'], [1, '★ 1']], number: true },
      { key: 'title', label: 'Headline', type: 'text' },
      { key: 'text', label: 'Review', type: 'textarea', required: true },
      { key: 'style', label: 'Colourway they bought (optional)', type: 'select', options: () => [['', '—'], ...palettes()] },
      { key: 'verified', label: 'Confirmed order', type: 'bool' },
      { key: 'hidden', label: 'Hide from the site', type: 'bool' },
    ],
  },
  {
    key: 'settings',
    title: 'Contact and payments',
    icon: '⚙️',
    kind: 'object',
    intro: 'How customers reach you and pay. Payment methods left blank are hidden at checkout.',
    defaults: () => ({ site: clone(SITE), payments: clone(PAYMENTS) }),
    fields: [
      { heading: 'Contact' },
      { key: 'site.whatsapp', label: 'WhatsApp number', type: 'text', help: 'With country code, digits only, e.g. 919064188260.', pattern: '^\\d{10,15}$' },
      { key: 'site.email', label: 'Shop email', type: 'text' },
      { advanced: true, key: 'site.web3formsKey', label: 'Web3Forms access key', type: 'text', help: 'Turns on the "Send by Email" buttons. Free from web3forms.com.' },
      { heading: 'Payments' },
      { key: 'payments.advancePercent', label: 'Advance to confirm an order (%)', type: 'number', min: 0, max: 100 },
      { key: 'payments.upi.id', label: 'UPI ID', type: 'text', help: 'e.g. parineeta365@okaxis' },
      { key: 'payments.upi.payeeName', label: 'UPI payee name', type: 'text' },
      { key: 'payments.bank.accountName', label: 'Bank account name', type: 'text' },
      { key: 'payments.bank.accountNumber', label: 'Bank account number', type: 'text' },
      { key: 'payments.bank.ifsc', label: 'IFSC', type: 'text' },
      { key: 'payments.bank.bankName', label: 'Bank name', type: 'text' },
      { advanced: true, key: 'payments.gatewayLink', label: 'Payment page link (Razorpay, Instamojo…)', type: 'text' },
      { key: 'payments.payAtShop', label: 'Offer pay at the shop / on delivery', type: 'bool' },
    ],
  },
  {
    key: 'lookbook',
    title: 'Lookbook photos',
    icon: '📷',
    kind: 'list',
    intro: 'The gallery of the shop\'s photography.',
    itemTitle: (l) => l.title || 'New photo',
    defaults: () => clone(LOOKBOOK),
    blank: () => ({ id: '', title: '', w: 800, h: 800 }),
    thumbKey: 'id',
    fields: [
      { key: 'id', label: 'Photo', type: 'media', photoOnly: true, required: true, sizeKeys: ['w', 'h'] },
      { key: 'title', label: 'Caption', type: 'text', required: true },
    ],
  },
  {
    key: 'trust',
    title: 'Celebrity visits',
    icon: '🌟',
    kind: 'list',
    intro: 'Photos of well-known visitors. Name a guest only with their permission.',
    itemTitle: (t) => t.caption || 'New photo',
    itemSub: (t) => t.guest || '',
    defaults: () => clone(TRUST),
    blank: () => ({ id: '', guest: '', caption: '' }),
    thumbKey: 'id',
    fields: [
      { key: 'id', label: 'Photo', type: 'media', photoOnly: true, required: true },
      { key: 'caption', label: 'Caption', type: 'text', required: true },
      { key: 'guest', label: 'Guest name (only with permission)', type: 'text' },
    ],
  },
  {
    key: 'services',
    title: 'Services',
    icon: '🖌️',
    kind: 'list',
    intro: 'Commissions such as backdrops, painted punjabi and mehendi.',
    itemTitle: (s) => s.title || 'New service',
    itemSub: (s) => s.bn || '',
    defaults: () => clone(SERVICES),
    blank: () => ({ id: '', title: '', bn: '', body: '', photo: null, size: 'std' }),
    normalize: (s) => ({ ...s, photo: s.photo || null }),
    thumbKey: 'photo',
    fields: [
      { key: 'title', label: 'Name (English)', type: 'text', required: true },
      { key: 'bn', label: 'Name (Bengali)', type: 'text', lang: 'bn' },
      { advanced: true, key: 'id', label: 'Service code', type: 'slug', from: 'title', required: true },
      { key: 'body', label: 'Description', type: 'textarea' },
      { key: 'photo', label: 'Photo', type: 'media', photoOnly: true },
      { advanced: true, key: 'size', label: 'Tile size', type: 'select', options: [['std', 'Standard'], ['wide', 'Wide'], ['tall', 'Tall']] },
    ],
  },
  {
    key: 'story',
    title: 'Wedding story',
    icon: '📖',
    kind: 'list',
    intro: 'The chapters of the wedding day, each tied to a product.',
    itemTitle: (c) => c.title || 'New chapter',
    itemSub: (c) => c.moment || '',
    defaults: () => clone(STORY),
    blank: () => ({ product: '', moment: '', title: '', body: '', photo: null }),
    normalize: (c) => ({ ...c, photo: c.photo?.type && c.photo?.id ? c.photo : null }),
    fields: [
      { key: 'moment', label: 'Moment (small heading)', type: 'text' },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'body', label: 'Text', type: 'textarea', required: true },
      { key: 'product', label: 'Product featured', type: 'select', options: productOptions, required: true },
      { key: 'photo.type', label: 'Real photo kind', type: 'select', options: [['', 'None'], ['photo', 'Photo'], ['reel', 'Film']] },
      { key: 'photo.id', label: 'Real photo or film', type: 'media' },
    ],
  },
  {
    key: 'announcement',
    title: 'Announcement bar',
    icon: '📣',
    kind: 'object',
    intro: 'A thin strip at the top of the website, e.g. "Puja orders close 20 Sept". Leave the dates empty to show it until you switch it off.',
    defaults: () => clone(ANNOUNCEMENT),
    fields: [
      { key: 'visible', label: 'Show the announcement', type: 'bool' },
      { key: 'text', label: 'Message', type: 'text', help: 'Keep it short: one line on a phone.' },
      { key: 'linkText', label: 'Link text (optional)', type: 'text' },
      { key: 'linkUrl', label: 'Link (optional)', type: 'text', pattern: '^(https://|/|#)', help: 'A full https:// address, or a part of this site like #collection.' },
      { advanced: true, key: 'startsAt', label: 'Show from (optional)', type: 'date' },
      { advanced: true, key: 'endsAt', label: 'Hide from (optional)', type: 'date' },
    ],
  },
  {
    key: 'homepage',
    title: 'Homepage text',
    icon: '🏠',
    kind: 'object',
    intro: 'The headline, big photo and the heading and intro of every section. The italic ending of a heading is typed separately.',
    defaults: () => clone(HOMEPAGE),
    fields: [
      { heading: 'Top of the page (hero)' },
      { key: 'hero.strip', label: 'Small Bengali line above the headline', type: 'text', lang: 'bn' },
      { key: 'hero.stripEn', label: 'Its English translation', type: 'text' },
      { key: 'hero.title', label: 'Headline', type: 'text', required: true },
      { key: 'hero.titleEm', label: 'Headline, highlighted ending (italic)', type: 'text' },
      { key: 'hero.sub', label: 'Line under the headline', type: 'textarea' },
      { key: 'hero.ctaText', label: 'WhatsApp button text', type: 'text' },
      { key: 'hero.photo', label: 'Big photo', type: 'media', photoOnly: true },
      { advanced: true, key: 'hero.photoAlt', label: 'Describe the photo (for blind visitors and Google)', type: 'text' },
      { advanced: true, key: 'hero.metaBn', label: 'Photo caption (Bengali)', type: 'text', lang: 'bn' },
      { advanced: true, key: 'hero.meta', label: 'Photo caption', type: 'text' },
      ...HOMEPAGE_SECTIONS.flatMap(([id, name]) => [
        { heading: name },
        { key: `${id}.title`, label: 'Heading', type: 'text' },
        { key: `${id}.titleEm`, label: 'Heading, highlighted ending (italic)', type: 'text' },
        { key: `${id}.lede`, label: 'Intro text', type: 'textarea' },
        { key: `${id}.hidden`, label: 'Hide this whole section', type: 'bool' },
      ]),
    ],
  },
  {
    key: 'stores',
    title: 'Shops and addresses',
    icon: '📍',
    kind: 'list',
    intro: 'Shown in "Visit us": addresses, phone numbers and the map. The first shop with a map search is the one on the map.',
    itemTitle: (s) => s.name || 'New shop',
    itemSub: (s) => `${String(s.address || '').split('\n')[0]}${s.hidden ? ' · hidden' : ''}`,
    defaults: () => clone(STORES),
    blank: () => ({ name: '', address: '', phones: '', mapsUrl: '', mapsQuery: '', hours: '', hidden: false }),
    fields: [
      { key: 'name', label: 'Shop name', type: 'text', required: true },
      { key: 'address', label: 'Address', type: 'textarea', required: true, help: 'One line per row.' },
      { key: 'phones', label: 'Phone numbers', type: 'textarea', help: 'One per line, e.g. +91 97342 41918' },
      { key: 'hours', label: 'Opening hours (optional)', type: 'text', help: 'e.g. Mon–Sat, 10am–8pm' },
      { key: 'mapsUrl', label: 'Google Maps link', type: 'text', pattern: '^https://', help: 'Open Google Maps, find the shop, press Share, then Copy link, and paste it here. It looks like https://maps.app.goo.gl/… The "Directions" button on the website opens this link.' },
      { advanced: true, key: 'mapsQuery', label: 'Place shown on the small map', type: 'text', help: 'What you would type into Google Maps to find the shop. Leave it empty to use the shop name and address.' },
      { key: 'hidden', label: 'Hide from the site', type: 'bool' },
    ],
  },
  {
    key: 'socials',
    title: 'Social media',
    icon: '🔗',
    kind: 'list',
    intro: 'Instagram, YouTube and Facebook links, shown in "Films and social", the footer and to Google.',
    itemTitle: (s) => PLATFORMS[s.platform]?.label || 'New link',
    itemSub: (s) => `${s.handle || s.url || ''}${s.hidden ? ' · hidden' : ''}`,
    defaults: () => clone(SOCIALS),
    blank: () => ({ platform: 'instagram', url: '', handle: '', hidden: false }),
    fields: [
      { key: 'platform', label: 'Platform', type: 'select', options: Object.entries(PLATFORMS).map(([k, v]) => [k, v.label]), required: true },
      { key: 'url', label: 'Link', type: 'text', required: true, pattern: '^https://', help: 'The full https:// address of your page. Links to other websites are ignored.' },
      { key: 'handle', label: 'Name shown under it', type: 'text', help: 'e.g. @parineeta_365' },
      { key: 'hidden', label: 'Hide from the site', type: 'bool' },
    ],
  },
  {
    key: 'videos',
    title: 'YouTube videos',
    icon: '▶️',
    kind: 'list',
    intro: 'YouTube videos shown in "Films and social". Paste the video link. The player only loads when a visitor presses play.',
    itemTitle: (v) => v.title || 'New video',
    itemSub: (v) => `${v.youtubeId || ''}${v.hidden ? ' · hidden' : ''}`,
    defaults: () => clone(VIDEOS),
    blank: () => ({ youtubeId: '', title: '', hidden: false }),
    fields: [
      { key: 'youtubeId', label: 'YouTube link', type: 'text', required: true, pattern: '(youtube\\.com|youtu\\.be|^[\\w-]{11}$)', help: 'e.g. https://www.youtube.com/watch?v=… or https://youtu.be/…' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'hidden', label: 'Hide from the site', type: 'bool' },
    ],
  },
  {
    key: 'seo',
    title: 'Google and sharing',
    icon: '🔎',
    kind: 'object',
    intro: 'How the homepage appears in Google results and when its link is shared on WhatsApp or Facebook. Product pages set their own from each product.',
    defaults: () => clone(SEO),
    fields: [
      { key: 'title', label: 'Page title in Google', type: 'text', help: 'About 50–60 characters.' },
      { key: 'description', label: 'Description in Google', type: 'textarea', help: 'About 150 characters. Leave empty to keep the built-in one.' },
      { key: 'ogTitle', label: 'Title when shared', type: 'text' },
      { key: 'ogDescription', label: 'Description when shared', type: 'text' },
      { key: 'ogImage', label: 'Picture when shared', type: 'media', photoOnly: true, help: 'Leave empty to keep the Parineeta brand picture.' },
    ],
  },
];

export const FILM_OPTIONS = films;
