// npm run cms:schemas — turns the admin's field definitions (frontend/src/admin/schemas.js) into JSON Schemas
// (draft-07 subset that pg_jsonschema accepts) and writes database/migrations/002_schemas.sql.
// It also checks that today's bundled content passes its own schema, so the backfill can't fail.
import { writeFileSync } from 'node:fs';
import { SECTIONS } from '../frontend/src/admin/schemas.js';
import { EXTRA_SCHEMAS } from '../frontend/src/cms/extra-schemas.js';

const TEXT_MAX = 20000;
const SLUG = '^[a-z0-9][a-z0-9-]*$';

function leaf(f) {
  const nullable = !f.required;
  const t = (base) => (nullable ? [base, 'null'] : base);
  switch (f.type) {
    case 'number': return { type: t('number'), ...(f.min != null ? { minimum: f.min } : {}) };
    case 'bool': return { type: t('boolean') };
    case 'multi': return { type: t('array'), items: { type: 'string' } };
    case 'slug': return f.required ? { type: 'string', pattern: SLUG } : { type: ['string', 'null'] };
    case 'list': return { type: t('array'), items: objectOf(f.of) };
    case 'exact-prices': return { type: t('array'), items: { type: 'object', properties: { pick: { type: 'object' }, price: { type: 'number', minimum: 0 } }, required: ['pick', 'price'] } };
    default: return { type: t('string'), maxLength: TEXT_MAX }; // text, textarea, select, media, date
  }
}

/** Builds an object schema from fields whose keys may be dotted paths (model.kind, photo.id). */
function objectOf(fields) {
  const root = { type: 'object', properties: {}, required: [] };
  for (const f of fields.filter((x) => x.key)) {
    const path = f.key.split('.');
    let node = root;
    path.slice(0, -1).forEach((k, i) => {
      node.properties[k] ??= { type: ['object', 'null'], properties: {}, required: [] };
      if (f.required && i === 0 && !node.required.includes(k)) node.required.push(k);
      node = node.properties[k];
    });
    const last = path.at(-1);
    node.properties[last] = leaf(f);
    if (f.required) node.required.push(last);
  }
  const prune = (n) => {
    if (!n.required?.length) delete n.required;
    Object.values(n.properties || {}).forEach(prune);
    if (n.items) prune(n.items);
    return n;
  };
  return prune(root);
}

export function buildSchemas() {
  const out = {};
  for (const s of SECTIONS) {
    out[s.key] = s.kind === 'list' ? { type: 'array', items: objectOf(s.fields) } : objectOf(s.fields);
  }
  return { ...out, ...EXTRA_SCHEMAS };
}

/* ---- a small draft-07-subset validator, used only for the self-check ---- */
const typeOf = (v) => (v === null ? 'null' : Array.isArray(v) ? 'array' : Number.isInteger(v) ? 'integer' : typeof v);
export function validate(schema, v, at = '$', errs = []) {
  if (schema.type) {
    const types = [].concat(schema.type);
    const t = typeOf(v);
    if (!types.includes(t) && !(t === 'integer' && types.includes('number'))) {
      errs.push(`${at}: expected ${types.join('|')}, got ${t}`);
      return errs;
    }
  }
  if (typeof v === 'string') {
    if (schema.maxLength != null && v.length > schema.maxLength) errs.push(`${at}: too long`);
    if (schema.pattern && !new RegExp(schema.pattern).test(v)) errs.push(`${at}: doesn't match ${schema.pattern}`);
    if (schema.enum && !schema.enum.includes(v)) errs.push(`${at}: not one of ${schema.enum}`);
  }
  if (typeof v === 'number' && schema.minimum != null && v < schema.minimum) errs.push(`${at}: below ${schema.minimum}`);
  if (v && typeof v === 'object' && !Array.isArray(v)) {
    for (const k of schema.required || []) if (v[k] == null) errs.push(`${at}.${k}: required`);
    for (const [k, s] of Object.entries(schema.properties || {})) if (k in v) validate(s, v[k], `${at}.${k}`, errs);
  }
  if (Array.isArray(v) && schema.items) v.forEach((x, i) => validate(schema.items, x, `${at}[${i}]`, errs));
  return errs;
}

const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop());
if (isMain) {
  const schemas = buildSchemas();
  const { DEFAULT_DOCS } = await import('../frontend/src/cms/defaults.js');
  let bad = 0;
  for (const [key, schema] of Object.entries(schemas)) {
    const doc = DEFAULT_DOCS[key];
    if (doc === undefined) { console.error(`✗ ${key}: no default document`); bad++; continue; }
    const errs = validate(schema, doc);
    if (errs.length) { console.error(`✗ ${key}:\n  ${errs.slice(0, 8).join('\n  ')}`); bad++; }
  }
  if (bad) process.exit(1);
  const q = (s) => `'${JSON.stringify(s).replace(/'/g, "''")}'`;
  const rows = Object.entries(schemas).map(([k, s]) => `  ('${k}', ${q(s)}::jsonb)`).join(',\n');
  writeFileSync(new URL('../database/migrations/002_schemas.sql', import.meta.url),
    `-- Generated by npm run cms:schemas. Do not edit by hand.\ninsert into public.content_schemas (key, schema) values\n${rows}\non conflict (key) do update set schema = excluded.schema;\n`);
  console.log(`✓ ${Object.keys(schemas).length} schemas; bundled defaults pass. Wrote database/migrations/002_schemas.sql`);
}
